/* Music Mosaic: local-first profile, public catalog search, explainable ranking. */
const CONTEXTS=[['open','✳','Open mind'],['focus','◫','Focus'],['sketch','✎','Sketching'],['move','↗','Moving'],['unwind','☾','Unwinding'],['together','◌','Together']];
const CONTEXT_TAGS={open:[],focus:['ambient','instrumental','minimal','downtempo','classical'],sketch:['ambient','experimental','jazz','art pop','electronic'],move:['dance','funk','hip hop','electronic','rock'],unwind:['ambient','downtempo','dream pop','folk','soul'],together:['pop','dance','funk','soul','disco']};
const defaultState=()=>({version:2,historyEnabled:false,seeds:[],context:'open',adventure:45,lens:'balanced',events:[],shuffle:0,visible:6});
let state=defaultState(),db=null,profileExists=false,candidates=[],loading=false,searchResults=[];
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validId=value=>/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value||'');
const timestamp=()=>new Date().toISOString();
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){resolve(null);return}const req=indexedDB.open('music-mosaic',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('profile'))req.result.createObjectStore('profile')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function readProfile(){return new Promise(resolve=>{if(!db){resolve(null);return}const req=db.transaction('profile','readonly').objectStore('profile').get('current');req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>resolve(null)})}
function saveProfile(){if(!db||!profileExists)return;db.transaction('profile','readwrite').objectStore('profile').put(structuredClone(state),'current')}
function deleteProfile(){if(db)db.transaction('profile','readwrite').objectStore('profile').delete('current')}
function record(kind,track=null){state.events.push({kind,trackId:track?.id||null,tags:track?.tags||[],artist:track?.artist||null,context:state.context,at:timestamp()});state.events=state.events.slice(-1500);if(state.historyEnabled)saveProfile()}
function latestReaction(id){return state.events.filter(e=>e.trackId===id&&['love','unlove','skip'].includes(e.kind)).at(-1)?.kind||null}
function normalizeTag(value){return String(value||'').toLowerCase().trim().replace(/[-_]+/g,' ').replace(/\s+/g,' ')}
function uniqueTags(values){return [...new Set(values.map(normalizeTag).filter(Boolean))]}
function tagList(meta){const groups=meta?.tag||{};return uniqueTags([...(groups.recording||[]),...(groups.artist||[]),...(groups.release_group||[])].map(x=>x.tag)).slice(0,12)}
function topTags(){const counts=new Map();for(const seed of state.seeds)for(const tag of seed.tags||[])counts.set(tag,(counts.get(tag)||0)+1);const latest=new Map();for(const e of state.events)if(e.trackId&&['love','unlove','skip'].includes(e.kind))latest.set(e.trackId,e);for(const e of latest.values()){const delta=e.kind==='love'?1.5:e.kind==='skip'?-0.3:0;for(const tag of e.tags||[])counts.set(tag,Math.max(0,(counts.get(tag)||0)+delta))}return [...counts].filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]).slice(0,6)}
let mbQueue=Promise.resolve(),lastMbCall=0;
function musicBrainz(url){const task=mbQueue.catch(()=>{}).then(async()=>{const gap=Math.max(0,1200-(Date.now()-lastMbCall));if(gap)await new Promise(r=>setTimeout(r,gap));lastMbCall=Date.now();for(let attempt=0;attempt<2;attempt++){const response=await fetch(url,{headers:{Accept:'application/json'}});if(response.ok)return response.json();if(![429,503].includes(response.status)||attempt===1)throw Error(`MusicBrainz is unavailable (${response.status}). Please try again.`);await new Promise(r=>setTimeout(r,1700))}});mbQueue=task.catch(()=>{});return task}
async function listenBrainz(path){const response=await fetch(`https://api.listenbrainz.org${path}`,{headers:{Accept:'application/json'}});if(!response.ok)throw Error(`ListenBrainz is unavailable (${response.status}). Please try again.`);return response.json()}
async function searchArtist(query){$('artistSearchResults').textContent='Searching MusicBrainz…';try{const url=`https://musicbrainz.org/ws/2/artist/?query=${encodeURIComponent(query)}&fmt=json&limit=6`;const data=await musicBrainz(url);searchResults=(data.artists||[]).filter(a=>validId(a.id)).slice(0,6);$('artistSearchResults').innerHTML=searchResults.length?searchResults.map((a,i)=>`<button type="button" data-result="${i}">${esc(a.name)}<small>${esc(a.disambiguation||a.country||a.type||'Artist')} · MusicBrainz</small></button>`).join(''):'No artist found. Try another spelling.';document.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>addArtist(searchResults[Number(b.dataset.result)])))}catch(error){$('artistSearchResults').textContent=error.message}}
async function addArtist(result){if(state.seeds.some(s=>s.id===result.id)){$('artistSearchResults').textContent='Already in your profile.';return}const seed={id:result.id,name:result.name,tags:[]};state.seeds.push(seed);record('add-artist');$('artistInput').value='';$('artistSearchResults').textContent=`Added ${result.name}. Finding music…`;render();try{const data=await listenBrainz(`/1/metadata/artist/?artist_mbids=${seed.id}&inc=tag`);const artist=Array.isArray(data)?data.find(a=>a.artist_mbid===seed.id||a.mbid===seed.id):null;seed.tags=uniqueTags((artist?.tag?.artist||[]).map(t=>t.tag)).slice(0,10);saveProfile();render()}catch{}await refreshCandidates()}
function radioMode(){return state.adventure<34?'easy':state.adventure<68?'medium':'hard'}
function collectRadio(value,seed,output,depth=0){if(depth>7||!value)return;if(Array.isArray(value)){for(const item of value)collectRadio(item,seed,output,depth+1);return}if(typeof value!=='object')return;if(validId(value.recording_mbid)){const id=value.recording_mbid;const existing=output.get(id)||{id,seedIds:[],similarArtist:value.similar_artist_name||'',artistId:value.similar_artist_mbid||'',listenCount:Number(value.total_listen_count)||0};if(!existing.seedIds.includes(seed.id))existing.seedIds.push(seed.id);output.set(id,existing)}for(const [key,child] of Object.entries(value))if(key!=='recording_mbid'&&typeof child==='object')collectRadio(child,seed,output,depth+1)}
function parseMetadata(radio,meta,recording){const entry=meta||{};const title=entry.recording?.name||entry.recording?.title||entry.recording_name||entry.name||recording?.title||'';const artist=entry.artist?.name||entry.artist_credit_name||recording?.['artist-credit']?.[0]?.name||radio.similarArtist||'';if(!title||!artist)return null;return {...radio,title,artist,album:entry.release?.name||'',tags:tagList(entry)}}
async function refreshCandidates(){if(!state.seeds.length){candidates=[];loading=false;render();return}loading=true;render();const chosen=Array.from({length:Math.min(5,state.seeds.length)},(_,i)=>state.seeds[(state.shuffle+i)%state.seeds.length]);const radio=new Map();let failures=0;const results=await Promise.allSettled(chosen.map(seed=>listenBrainz(`/1/lb-radio/artist/${seed.id}?mode=${radioMode()}&max_similar_artists=12&max_recordings_per_artist=2&pop_begin=0&pop_end=100`)));results.forEach((result,i)=>{if(result.status==='fulfilled')collectRadio(result.value,chosen[i],radio);else failures++});const ids=[...radio.keys()].slice(0,12);if(!ids.length){loading=false;candidates=[];$('resultStatus').textContent=failures?'The music service is unavailable. Reshuffle to try again.':'No matches came back. Try another artist.';render();return}try{const data=await listenBrainz(`/1/metadata/recording/?recording_mbids=${ids.join(',')}&inc=artist%20tag%20release`);const recordings=await Promise.allSettled(ids.map(id=>musicBrainz(`https://musicbrainz.org/ws/2/recording/${id}?fmt=json`)));candidates=ids.map((id,i)=>parseMetadata(radio.get(id),data?.[id],recordings[i].status==='fulfilled'?recordings[i].value:null)).filter(Boolean).filter(t=>!state.seeds.some(s=>s.id===t.artistId));$('resultStatus').textContent=candidates.length?`Found ${candidates.length} candidates through ListenBrainz.`:'Recording titles are unavailable right now. Reshuffle to try again.'}catch(error){candidates=[];$('resultStatus').textContent=error.message}loading=false;state.visible=6;render()}
function score(track){const tagWeights=new Map(topTags());const matching=track.tags.reduce((sum,tag)=>sum+(tagWeights.get(tag)||0),0);const contextTags=CONTEXT_TAGS[state.context]||[];const context=track.tags.filter(tag=>contextTags.some(c=>tag.includes(c)||c.includes(tag))).length;const shared=track.seedIds.length;const popularity=Math.log10(track.listenCount+1)/7;const discovery=state.adventure/100;const tagFactor=state.lens==='tags'?1.5:state.lens==='listeners'?.5:1;const sharedFactor=state.lens==='listeners'?1.6:state.lens==='tags'?.7:1;const feedback=latestReaction(track.id);const jitter=(hash(track.id+state.shuffle)%100)/250;return shared*1.7*sharedFactor+matching*.35*tagFactor+context*.45+((1-discovery)*popularity+discovery*(1-popularity))*.9+(feedback==='love'?1.2:feedback==='skip'?-100:0)+jitter}
function hash(value){let n=0;for(const c of value)n=(n*31+c.charCodeAt(0))|0;return Math.abs(n)}
function ranked(){const rest=[...candidates],chosen=[];while(rest.length){let best=-Infinity,index=0;rest.forEach((track,i)=>{const sameArtist=chosen.filter(x=>x.artist===track.artist).length;const sameTag=chosen.slice(-3).filter(x=>x.tags[0]&&x.tags[0]===track.tags[0]).length;const value=score(track)-sameArtist*2-sameTag*.55;if(value>best){best=value;index=i}});chosen.push(rest.splice(index,1)[0])}return chosen}
function reason(track){const names=state.seeds.filter(s=>track.seedIds.includes(s.id)).map(s=>s.name);const path=names.length>1?`Found through listeners connected to ${names.slice(0,2).join(' and ')}.`:names.length?`Found through listeners connected to ${names[0]}.`:'Found through a nearby listening path.';const tags=track.tags.length?` Community tags include ${track.tags.slice(0,2).join(' and ')}.`:'';const context=(CONTEXT_TAGS[state.context]||[]).some(c=>track.tags.some(t=>t.includes(c)))?' Tags also match this listening context.':'';return path+tags+context}
function providerLink(provider,track){const query=encodeURIComponent(`${track.title} ${track.artist}`);return provider==='spotify'?`https://open.spotify.com/search/${query}`:`https://music.apple.com/search?term=${query}`}
function renderContexts(){$('contextGrid').innerHTML=CONTEXTS.map(([id,icon,label])=>`<button type="button" class="${state.context===id?'active':''}" data-context="${id}" aria-pressed="${state.context===id}"><span aria-hidden="true">${icon}</span>${label}</button>`).join('');document.querySelectorAll('[data-context]').forEach(b=>b.addEventListener('click',()=>{state.context=b.dataset.context;record('context');render()}))}
function renderSeeds(){$('seedGrid').innerHTML=state.seeds.map(seed=>`<button type="button" class="active" data-remove="${esc(seed.id)}" aria-label="Remove ${esc(seed.name)}"><span aria-hidden="true">−</span>${esc(seed.name)}</button>`).join('');$('selectedCount').textContent=`${state.seeds.length} SELECTED`;document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.seeds=state.seeds.filter(s=>s.id!==b.dataset.remove);record('remove-artist');refreshCandidates()}))}
function renderBars(){const tags=topTags(),maximum=Math.max(1,...tags.map(([,weight])=>weight));$('tasteBars').innerHTML=tags.length?tags.map(([tag,weight])=>`<div class="taste-bar"><div class="bar-labels"><span>${esc(tag)}</span><span>${Math.round(weight/maximum*100)}%</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.round(weight/maximum*100)}%"></div></div></div>`).join(''):'<p class="micro-note">Add artists or love a track to see your community tag mix.</p>'}
function emptyResults(){const message=loading?'Finding paths through the music catalog…':state.seeds.length?'No recommendations yet. Try another artist or reshuffle.':'Start with one artist you like. Your profile is empty until you add them.';$('recommendations').innerHTML=`<div class="empty-results"><div class="empty-symbol">✳</div><strong>${loading?'Tuning in…':'Your mix starts here.'}</strong><p>${esc(message)} ${!state.seeds.length?'<a href="#taste">Add an artist ↓</a>':''}</p></div>`;$('resultsCount').textContent='00—00';$('moreButton').hidden=true}
function renderRecommendations(){if(!candidates.length){emptyResults();return}const tracks=ranked().slice(0,state.visible);$('resultsCount').textContent=`01—${String(tracks.length).padStart(2,'0')}`;$('moreButton').hidden=tracks.length>=candidates.length||tracks.length>=18;$('recommendations').innerHTML=tracks.map((track,i)=>`<article class="recommendation"><div class="rec-index">${String(i+1).padStart(2,'0')}</div><div class="rec-main"><div class="rec-title">${esc(track.title)}</div><div class="rec-artist">${esc(track.artist)}${track.album?' · '+esc(track.album):''}</div><p class="rec-reason">${esc(reason(track))}</p><div class="rec-tags">${track.tags.slice(0,3).map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></div><div class="rec-actions"><a class="listen" href="${providerLink('spotify',track)}" target="_blank" rel="noopener noreferrer" data-open="${esc(track.id)}">Spotify ↗</a><a href="${providerLink('apple',track)}" target="_blank" rel="noopener noreferrer" data-open="${esc(track.id)}">Apple Music ↗</a><button type="button" data-love="${esc(track.id)}" class="${latestReaction(track.id)==='love'?'chosen':''}" aria-pressed="${latestReaction(track.id)==='love'}">${latestReaction(track.id)==='love'?'♥ Loved':'♡ Love'}</button><button type="button" data-skip="${esc(track.id)}" aria-label="Not for me: ${esc(track.title)}">Not for me</button></div></article>`).join('');document.querySelectorAll('[data-love]').forEach(b=>b.addEventListener('click',()=>{const track=candidates.find(t=>t.id===b.dataset.love);record(latestReaction(track.id)==='love'?'unlove':'love',track);render()}));document.querySelectorAll('[data-skip]').forEach(b=>b.addEventListener('click',()=>{record('skip',candidates.find(t=>t.id===b.dataset.skip));render()}));document.querySelectorAll('[data-open]').forEach(a=>a.addEventListener('click',()=>record('opened',candidates.find(t=>t.id===a.dataset.open))))}
function renderDialog(){const saved=new Set();for(const e of state.events){if(e.kind==='love')saved.add(e.trackId);if(e.kind==='unlove')saved.delete(e.trackId)}$('historyToggle').textContent=state.historyEnabled?'Pause':'Enable';$('historyToggle').classList.toggle('on',state.historyEnabled);$('historyToggle').setAttribute('aria-pressed',String(state.historyEnabled));$('historyStatus').textContent=state.historyEnabled?'On — saved on this device':profileExists?'Paused — saved history retained':'Off — this session only';$('eventCount').textContent=state.events.length;$('savedCount').textContent=saved.size}
function render(){renderContexts();renderSeeds();renderBars();renderRecommendations();renderDialog();$('adventureRange').value=state.adventure;$('adventureValue').textContent=state.adventure<34?'Keep it close':state.adventure<68?'A little curious':'Take me somewhere new';document.querySelectorAll('[data-lens]').forEach(b=>b.classList.toggle('active',b.dataset.lens===state.lens));if(typeof renderGraph==='function')renderGraph()}
function feedback(message){$('dialogFeedback').textContent=message;setTimeout(()=>{$('dialogFeedback').textContent=''},5000)}
function exportJson(){const data={...state,app:'Music Mosaic',exportedAt:timestamp()};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`music-mosaic-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);feedback('Profile exported.')}
async function importJson(file){if(!file)return;try{if(file.size>5_000_000)throw Error('That file is too large.');const data=JSON.parse(await file.text());if(data.app!=='Music Mosaic'||data.version!==2||!Array.isArray(data.seeds)||!Array.isArray(data.events))throw Error('This is not a supported Music Mosaic export.');state={...defaultState(),...data,seeds:data.seeds.filter(s=>validId(s.id)&&typeof s.name==='string').slice(0,50),events:data.events.filter(e=>e&&typeof e.kind==='string'&&typeof e.at==='string').slice(-1500),visible:6};delete state.app;delete state.exportedAt;state.historyEnabled=true;profileExists=true;saveProfile();render();await refreshCandidates();feedback('Profile imported.')}catch(error){feedback(error.message||'Could not import that file.')}finally{$('importFile').value=''}}
function wire(){$('settingsButton').addEventListener('click',()=>$('dataDialog').showModal());$('dataButton').addEventListener('click',()=>$('dataDialog').showModal());$('closeDialog').addEventListener('click',()=>$('dataDialog').close());$('dataDialog').addEventListener('click',e=>{if(e.target===$('dataDialog'))$('dataDialog').close()});$('historyToggle').addEventListener('click',()=>{if(!db){feedback('Browser storage is unavailable. This session still works.');return}state.historyEnabled=!state.historyEnabled;if(state.historyEnabled)profileExists=true;saveProfile();renderDialog();feedback(state.historyEnabled?'Local history enabled.':'History paused. Existing data stays until you delete it.')});$('artistForm').addEventListener('submit',e=>{e.preventDefault();const query=$('artistInput').value.trim();if(query)searchArtist(query)});$('exportButton').addEventListener('click',exportJson);$('importFile').addEventListener('change',e=>importJson(e.target.files[0]));$('clearButton').addEventListener('click',()=>{if(!confirm('Delete your saved activity and artist choices on this device?'))return;state=defaultState();profileExists=false;candidates=[];deleteProfile();render();feedback('Local profile deleted.')});$('adventureRange').addEventListener('input',e=>{state.adventure=Number(e.target.value);render()});$('adventureRange').addEventListener('change',()=>{record('adventure');refreshCandidates()});document.querySelectorAll('[data-lens]').forEach(b=>b.addEventListener('click',()=>{state.lens=b.dataset.lens;record('lens');render()}));$('refreshButton').addEventListener('click',()=>{state.shuffle++;record('reshuffle');refreshCandidates()});$('moreButton').addEventListener('click',()=>{state.visible=Math.min(18,state.visible+6);renderRecommendations()});if(typeof wireGraph==='function')wireGraph()}
async function init(){try{db=await openDb();const saved=await readProfile();if(saved?.version===2&&Array.isArray(saved.seeds)&&Array.isArray(saved.events)){state={...defaultState(),...saved,visible:6};profileExists=true}}catch(error){console.warn('Browser storage unavailable; using session only.',error)}wire();render();if(!profileExists)$('dataDialog').showModal();if(state.seeds.length)refreshCandidates()}
init();
